### PR TITLE
Upstream changes

### PR DESCRIPTION
**Pull request by jeffmon**

### CODE REVIEW

**Comment by jeffmon** [comment]
@lukebaker It looks like I don't have write access to this repo, any chance you can take a look at this? Thanks!

**Comment by lukebaker** [comment]
@jeffmon I've given you write access. Do you still want me to take a look at this?

**Comment by jeffmon** [comment]
@lukebaker Thanks for that! Would it be wise to merge in **all of the things** from their `dev` branch in the first place? And yes, would you be able to take a look? 😬

**Comment by lukebaker** [comment]
Seem my changes in #4. I think that does what we want.

**Pull request closed without merging**
